default_language_version:
    python: python3.12

exclude: 'docs|.git|.tox'

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-yaml
      - id: check-json
      - id: check-ast
      - id: check-merge-conflict
      - id: check-added-large-files
        args: [ '--maxkb=1997' ]
      - id: trailing-whitespace
        exclude_types: [ svg ]
      - id: end-of-file-fixer
        exclude_types: [ svg ]
      - id: debug-statements

  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black

  - repo: https://github.com/rtts/djhtml
    rev: 3.0.8
    hooks:
      - id: djhtml

  - repo: https://github.com/PyCQA/flake8
    rev: 7.3.0
    hooks:
      - id: flake8
        args: ['--config=setup.cfg']
        additional_dependencies: [
            "flake8-simplify == 0.19.3",
        ]

  - repo: https://github.com/asottile/reorder_python_imports
    rev: v3.15.0
    hooks:
      - id: reorder-python-imports
        args: [--py312-plus]

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.20.0
    hooks:
      - id: pyupgrade
        args: [--py312-plus]
